// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3ZlrVBn3y_N-LTCVMxKzxYGOUQrn9ywc',
    appId: '1:747104098843:web:57f9e0934f3326cebaf6be',
    messagingSenderId: '747104098843',
    projectId: 'my-angadi',
    authDomain: 'my-angadi.firebaseapp.com',
    storageBucket: 'my-angadi.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyc4boxwQ0kJjE4Id3g55e8uYzjr8pcg4',
    appId: '1:747104098843:android:3c8dd445dfdc515ebaf6be',
    messagingSenderId: '747104098843',
    projectId: 'my-angadi',
    storageBucket: 'my-angadi.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMGFoDgT8VHHbjKT08ZarojQtXPYXpDfQ',
    appId: '1:747104098843:ios:04293ab9070adf03baf6be',
    messagingSenderId: '747104098843',
    projectId: 'my-angadi',
    storageBucket: 'my-angadi.appspot.com',
    iosBundleId: 'com.segar.myangadi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMGFoDgT8VHHbjKT08ZarojQtXPYXpDfQ',
    appId: '1:747104098843:ios:549a86d00263d668baf6be',
    messagingSenderId: '747104098843',
    projectId: 'my-angadi',
    storageBucket: 'my-angadi.appspot.com',
    iosBundleId: 'com.segar.myangadi.RunnerTests',
  );
}
